### ISSUE TITLE
Container keeps restarting - exit code 0

### ISSUE THREAD

**Issue by varunpan** [Benuhx/pgadmin4-docker-arm#3]
My system:
device: Raspberry pi 4gb arm7l
OS: rasbian lite (debian 11)

My docker compose file
```
version: '3.0'
services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - /home/mainpi/.docker/postgres:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      homelan:
        ipv4_address: 172.18.5.194
  pgadmin:
    container_name: pgadmin
    image: benuhx/pgadmin4-pi:latest
    environment:
      PGADMIN_SETUP_EMAIL: ${PGADMIN_SETUP_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_SETUP_PASSWORD: ${PGADMIN_SETUP_PASSWORD:-admin}
    volumes:
      - /home/mainpi/.docker/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:5050"
    restart: always
    networks:
      homelan:
        ipv4_address: 172.18.5.193
networks:
  homelan:
    external: true
```
when i load this, the postgres work fine,  but pgadmin keeps restart and showing the following message:
`pgadmin exited with code 0`
